import type { UserProfile } from "@/lib/profile/types";

export const CURRENT_USER_ID = "me";

export const SEED_PROFILES: UserProfile[] = [
  {
    id: CURRENT_USER_ID,
    username: "azewejigwum",
    firstName: "Azewene",
    lastName: "Njigwum",
    email: "azee.builds@gmail.com",
    bio: "Product designer and frontend builder helping teams ship clear, calm digital products.",
    headline: "Product Designer · Frontend",
    location: "Remote",
    roleLabel: "Designer · Engineer",
    availability: "open_to_work",
    verified: true,
    joinedAt: "2026-01-12",
    followers: ["u2", "u3"],
    following: ["u2"],
    listingCount: 3,
    social: {
      linkedIn: "https://linkedin.com/in/azewejigwum",
      github: "https://github.com",
      instagram: "",
      facebook: "",
    },
  },
  {
    id: "u2",
    username: "sammyakindele",
    firstName: "Sammy",
    lastName: "Akindele",
    email: "sammy@example.com",
    bio: "Experienced Lagos property agent helping clients buy, sell, and rent verified homes across the city.",
    headline: "Residential · Commercial Agent",
    location: "Lagos, Lagos",
    roleLabel: "Residential · Commercial Agent",
    availability: "available",
    verified: true,
    joinedAt: "2025-11-04",
    followers: ["me"],
    following: ["me", "u3"],
    listingCount: 1,
    social: {
      linkedIn: "https://linkedin.com",
      instagram: "https://instagram.com",
      facebook: "https://facebook.com",
    },
  },
  {
    id: "u3",
    username: "priya.codes",
    firstName: "Priya",
    lastName: "Shah",
    email: "priya@example.com",
    bio: "Full-stack engineer focused on thoughtful UX and reliable systems.",
    headline: "Software Engineer",
    location: "Toronto, ON",
    roleLabel: "Engineer · Mentor",
    availability: "busy",
    verified: false,
    joinedAt: "2026-03-01",
    followers: ["me", "u2"],
    following: [],
    listingCount: 0,
    social: {
      linkedIn: "https://linkedin.com",
      github: "https://github.com",
    },
  },
];
