import type { CorePillar, DevTool, WorkspaceModule } from "./types";
import { moduleCustomIconSrc } from "@/lib/workspace-icons";

/** Overview modules from ctrlbugs/Thewrker — hrefs mapped into this app's /dashboard routes */
export const WORKSPACE_MODULES: WorkspaceModule[] = [
  {
    id: "text-editor",
    title: "Text Editor",
    description: "Write and edit plain text, markdown, config files, and data formats.",
    icon: moduleCustomIconSrc("text-editor", "/assets/icons/text-editor.svg"),
    accentColor: "#e8f1ff",
    accentStrong: "#4A6FA5",
    href: "/dashboard/studios/text",
    formats: ["TXT", "MD", "JSON", "XML", "CSV", "YAML"],
    features: ["Find & Replace", "Word Count", "Auto Save", "Line & Character Stats"],
  },
  {
    id: "pdf-studio",
    title: "PDF Studio",
    description: "Merge, split, and manage PDF documents in your browser.",
    icon: moduleCustomIconSrc("pdf-studio", "/assets/icons/pdf-acrobat.svg"),
    accentColor: "#ffe8e8",
    accentStrong: "#E85D5D",
    href: "/dashboard/studios/pdf",
    formats: ["PDF"],
    features: ["Merge PDFs", "Split by Page Range", "Split Every Page", "Download Instantly"],
  },
  {
    id: "image-studio",
    title: "Image Studio",
    description: "Resize, compress, convert, and remove image backgrounds in your browser.",
    icon: moduleCustomIconSrc("image-studio", "/assets/icons/image.svg"),
    accentColor: "#ffe8f3",
    accentStrong: "#D66BA0",
    href: "/dashboard/studios/image",
    formats: ["PNG", "JPG", "WEBP", "SVG", "ICO", "BMP"],
    features: ["Remove Background", "Resize", "Compress", "Convert Formats"],
  },
  {
    id: "archive-studio",
    title: "Archive Studio",
    description: "Create, extract, and compress ZIP archives in your workspace.",
    icon: moduleCustomIconSrc("archive-studio", "/assets/icons/archive.svg"),
    accentColor: "#e7f7f9",
    accentStrong: "#3A9AA6",
    href: "/dashboard/studios/archive",
    formats: ["ZIP"],
    features: ["Create ZIP", "Compress ZIP", "Extract ZIP", "Compression Level Control"],
  },
  {
    id: "converter-hub",
    title: "Converter Hub",
    description: "Convert audio and video formats without leaving your workspace.",
    icon: moduleCustomIconSrc("converter-hub", "/assets/icons/converter.svg"),
    accentColor: "#efe9ff",
    accentStrong: "#7B6CCF",
    href: "/dashboard/studios/converter",
    formats: ["MP3", "WAV", "AAC", "MP4", "MOV", "AVI"],
    features: ["MP3 ↔ WAV", "MP4 ↔ MOV", "MP4 → MP3", "AVI ↔ MP4"],
  },
  {
    id: "compressor-studio",
    title: "Compressor Studio",
    description: "Shrink image, audio, and video file sizes without leaving your workspace.",
    icon: moduleCustomIconSrc("compressor-studio", "/assets/icons/files.svg"),
    accentColor: "#e8f6ef",
    accentStrong: "#3D9B6E",
    href: "/dashboard/studios/compressor",
    formats: ["JPG", "WEBP", "PNG", "MP3", "MP4"],
    features: ["Image Compress", "Audio Compress", "Video Compress", "Size Savings"],
  },
  {
    id: "ai-studio",
    title: "AI Studio",
    description: "Check documents for originality, repetition, and similarity patterns.",
    icon: moduleCustomIconSrc("ai-studio", "/assets/icons/ai.svg"),
    accentColor: "#e8f5f7",
    accentStrong: "#76BEC5",
    href: "/dashboard/studios/ai",
    formats: ["PDF", "DOCX", "TXT", "MD", "RTF"],
    features: ["Plagiarism Check", "Upload or Paste", "Reference Compare", "Local Analysis"],
  },
];

export const DEV_TOOLS: DevTool[] = [
  {
    id: "json-formatter",
    title: "JSON Formatter",
    description: "Format, minify, and validate JSON instantly.",
    icon: moduleCustomIconSrc("json-formatter", "/assets/icons/json.svg"),
    href: "/dashboard/tools/json",
    accentColor: "#eef3ff",
    accentStrong: "#5B7CBA",
  },
  {
    id: "base64",
    title: "Base64 Encoder",
    description: "Encode and decode Base64 text.",
    icon: moduleCustomIconSrc("base64", "/assets/icons/base64.svg"),
    href: "/dashboard/tools/base64",
    accentColor: "#e8f7f4",
    accentStrong: "#3D9B88",
  },
  {
    id: "uuid",
    title: "UUID Generator",
    description: "Generate unique identifiers on demand.",
    icon: moduleCustomIconSrc("uuid", "/assets/icons/uuid.svg"),
    href: "/dashboard/tools/uuid",
    accentColor: "#fff3e8",
    accentStrong: "#D4894A",
  },
  {
    id: "hash",
    title: "Hash Generator",
    description: "Create SHA-256, SHA-384, and SHA-512 hashes.",
    icon: moduleCustomIconSrc("hash", "/assets/icons/hash.svg"),
    href: "/dashboard/tools/hash",
    accentColor: "#f3eaff",
    accentStrong: "#8B6CCF",
  },
  {
    id: "jwt",
    title: "JWT Decoder",
    description: "Inspect JWT headers and payloads safely.",
    icon: moduleCustomIconSrc("jwt", "/assets/icons/jwt.svg"),
    href: "/dashboard/tools/jwt",
    accentColor: "#e8f0ff",
    accentStrong: "#4A6FA5",
  },
  {
    id: "regex",
    title: "Regex Tester",
    description: "Test patterns, flags, and replacements live.",
    icon: moduleCustomIconSrc("regex", "/assets/icons/regex.svg"),
    href: "/dashboard/tools/regex",
    accentColor: "#ffeef2",
    accentStrong: "#C45B7A",
  },
];
export const CORE_PILLARS: CorePillar[] = [
  {
    id: "workspaces",
    title: "Workspaces",
    description:
      "Every project gets files, chat, meetings, tasks, notes, AI, and team members in one place.",
    accentColor: "#d8fcf7",
  },
  {
    id: "file-engine",
    title: "Universal File Engine",
    description:
      "Open documents, code, media, and archives without switching applications.",
    accentColor: "#e0f3fa",
  },
  {
    id: "ai",
    title: "AI Workspace Assistant",
    description:
      "Analyze documents for originality and similarity directly in your browser.",
    accentColor: "#f4f0fe",
  },
];
