import type { OrgState } from "./types";

const day = (offset: number, hour = 10) => {
  const d = new Date();
  d.setDate(d.getDate() + offset);
  d.setHours(hour, 0, 0, 0);
  return d.toISOString();
};

/** Demo organisation HQ — fully interactive in local staging */
export function createSeedState(): OrgState {
  return {
    currentUserId: "e1",
    clockedIn: false,
    departments: [
      {
        id: "d1",
        name: "Engineering",
        headId: "e2",
        description: "Product engineering, platform, and quality.",
        kpis: ["Sprint velocity", "Bug escape rate", "Uptime"],
      },
      {
        id: "d2",
        name: "People & Culture",
        headId: "e4",
        description: "HR, talent, and employee experience.",
        kpis: ["Time-to-hire", "Engagement score", "Retention"],
      },
      {
        id: "d3",
        name: "Operations",
        headId: "e5",
        description: "Day-to-day delivery and process excellence.",
        kpis: ["SLA adherence", "Cost efficiency", "Process cycle time"],
      },
    ],
    teams: [
      { id: "t1", name: "Platform", departmentId: "d1", leadId: "e2" },
      { id: "t2", name: "Product Design", departmentId: "d1", leadId: "e3" },
      { id: "t3", name: "People Ops", departmentId: "d2", leadId: "e4" },
      { id: "t4", name: "Workplace Ops", departmentId: "d3", leadId: "e5" },
    ],
    employees: [
      {
        id: "e1",
        employeeId: "TW-1001",
        firstName: "Alex",
        lastName: "Morgan",
        email: "alex.morgan@thewrker.com",
        phone: "+1 555 0101",
        jobTitle: "Product Designer",
        departmentId: "d1",
        teamId: "t2",
        managerId: "e2",
        status: "active",
        skills: ["Figma", "Design Systems", "User Research"],
        certifications: ["Google UX Certificate"],
        leaveBalance: 14,
        performanceRating: 4.6,
        avatarColor: "#76BEC5",
      },
      {
        id: "e2",
        employeeId: "TW-1002",
        firstName: "Jordan",
        lastName: "Lee",
        email: "jordan.lee@thewrker.com",
        phone: "+1 555 0102",
        jobTitle: "Engineering Manager",
        departmentId: "d1",
        teamId: "t1",
        status: "active",
        skills: ["Leadership", "React", "System Design"],
        certifications: ["PMP"],
        leaveBalance: 10,
        performanceRating: 4.8,
        avatarColor: "#21386B",
        isManager: true,
      },
      {
        id: "e3",
        employeeId: "TW-1003",
        firstName: "Sam",
        lastName: "Rivera",
        email: "sam.rivera@thewrker.com",
        phone: "+1 555 0103",
        jobTitle: "Frontend Engineer",
        departmentId: "d1",
        teamId: "t1",
        managerId: "e2",
        status: "active",
        skills: ["TypeScript", "Next.js", "Accessibility"],
        certifications: [],
        leaveBalance: 18,
        performanceRating: 4.4,
        avatarColor: "#4A6FA5",
      },
      {
        id: "e4",
        employeeId: "TW-1004",
        firstName: "Priya",
        lastName: "Shah",
        email: "priya.shah@thewrker.com",
        phone: "+1 555 0104",
        jobTitle: "Head of People",
        departmentId: "d2",
        teamId: "t3",
        status: "active",
        skills: ["HR Ops", "Coaching", "Policy"],
        certifications: ["SHRM-CP"],
        leaveBalance: 12,
        performanceRating: 4.7,
        avatarColor: "#D66BA0",
        isManager: true,
      },
      {
        id: "e5",
        employeeId: "TW-1005",
        firstName: "Chris",
        lastName: "Okeke",
        email: "chris.okeke@thewrker.com",
        phone: "+1 555 0105",
        jobTitle: "Operations Lead",
        departmentId: "d3",
        teamId: "t4",
        status: "active",
        skills: ["Process Design", "Analytics", "Vendor Mgmt"],
        certifications: ["Lean Six Sigma"],
        leaveBalance: 9,
        performanceRating: 4.5,
        avatarColor: "#3D9B6E",
        isManager: true,
      },
      {
        id: "e6",
        employeeId: "TW-1006",
        firstName: "Maya",
        lastName: "Chen",
        email: "maya.chen@thewrker.com",
        phone: "+1 555 0106",
        jobTitle: "People Partner",
        departmentId: "d2",
        teamId: "t3",
        managerId: "e4",
        status: "on-leave",
        skills: ["Employee Relations", "Onboarding"],
        certifications: [],
        leaveBalance: 3,
        performanceRating: 4.2,
        avatarColor: "#E85D5D",
      },
    ],
    tasks: [
      {
        id: "task1",
        title: "Finalize Organisation dashboard polish",
        description: "Ship the employee HQ experience with working modules.",
        notes: "Prioritize tasks, leave, and directory first.",
        priority: "high",
        dueDate: day(2, 17),
        assignedBy: "e2",
        assignedTo: "e1",
        status: "in_progress",
        progress: 65,
        createdAt: day(-3),
        comments: [
          {
            id: "c1",
            authorId: "e2",
            text: "Looking sharp — keep the UX calm and actionable.",
            at: day(-1, 15),
          },
        ],
      },
      {
        id: "task2",
        title: "Prepare Q3 team OKR draft",
        description: "Outline department goals and key results for review.",
        notes: "",
        priority: "medium",
        dueDate: day(5, 12),
        assignedBy: "e2",
        assignedTo: "e1",
        status: "new",
        progress: 0,
        createdAt: day(-1),
        comments: [],
      },
      {
        id: "task3",
        title: "Review accessibility checklist",
        description: "Audit key workspace flows for WCAG AA.",
        notes: "Focus on forms and tables.",
        priority: "urgent",
        dueDate: day(-1, 16),
        assignedBy: "e2",
        assignedTo: "e3",
        status: "overdue",
        progress: 40,
        createdAt: day(-6),
        comments: [],
      },
      {
        id: "task4",
        title: "Update employee handbook excerpt",
        description: "Sync leave policy language for announcements.",
        notes: "",
        priority: "low",
        dueDate: day(7, 11),
        assignedBy: "e4",
        assignedTo: "e4",
        status: "pending_review",
        progress: 90,
        createdAt: day(-4),
        comments: [],
      },
      {
        id: "task5",
        title: "Ops weekly capacity report",
        description: "Summarize workload distribution across teams.",
        notes: "",
        priority: "medium",
        dueDate: day(1, 14),
        assignedBy: "e5",
        assignedTo: "e5",
        status: "completed",
        progress: 100,
        createdAt: day(-5),
        comments: [],
      },
    ],
    meetings: [
      {
        id: "m1",
        title: "Engineering standup",
        agenda: "Blockers, priorities, demos",
        startsAt: day(0, 9),
        durationMins: 30,
        hostId: "e2",
        attendeeIds: ["e1", "e2", "e3"],
        link: "https://meet.google.com/thewrker-standup",
        provider: "Google Meet",
        notes: "",
      },
      {
        id: "m2",
        title: "People ops sync",
        agenda: "Leave approvals, onboarding pipeline",
        startsAt: day(1, 15),
        durationMins: 45,
        hostId: "e4",
        attendeeIds: ["e4", "e6", "e2"],
        link: "https://zoom.us/j/thewrker-people",
        provider: "Zoom",
        notes: "",
      },
      {
        id: "m3",
        title: "Organisation launch briefing",
        agenda: "Rollout plan, training, feedback loops",
        startsAt: day(3, 11),
        durationMins: 60,
        hostId: "e5",
        attendeeIds: ["e1", "e2", "e3", "e4", "e5"],
        link: "https://teams.microsoft.com/l/meetup-join/thewrker",
        provider: "Microsoft Teams",
        notes: "Bring department KPI snapshots.",
      },
    ],
    leaveRequests: [
      {
        id: "l1",
        employeeId: "e1",
        type: "annual",
        from: day(10).slice(0, 10),
        to: day(12).slice(0, 10),
        reason: "Family travel",
        status: "pending",
        createdAt: day(-1),
      },
      {
        id: "l2",
        employeeId: "e6",
        type: "sick",
        from: day(-2).slice(0, 10),
        to: day(1).slice(0, 10),
        reason: "Recovery",
        status: "approved",
        createdAt: day(-3),
      },
    ],
    announcements: [
      {
        id: "a1",
        title: "Welcome to Organisation HQ",
        body: "Your intelligent employee workspace is live. Use Tasks, Leave, Meetings, and Chat from one place.",
        authorId: "e4",
        category: "news",
        createdAt: day(-2),
        pinned: true,
      },
      {
        id: "a2",
        title: "Holiday calendar published",
        body: "Company holidays for the next quarter are now available under Leave & Attendance.",
        authorId: "e4",
        category: "holiday",
        createdAt: day(-5),
      },
      {
        id: "a3",
        title: "Security reminder: enable 2FA",
        body: "All employees should confirm two-factor authentication on their account this week.",
        authorId: "e5",
        category: "policy",
        createdAt: day(-1),
      },
    ],
    notifications: [
      {
        id: "n1",
        title: "New task assigned",
        body: "Finalize Organisation dashboard polish is due in 2 days.",
        type: "task",
        createdAt: day(-1, 9),
        read: false,
        href: "/dashboard/organisation/tasks",
      },
      {
        id: "n2",
        title: "Meeting today",
        body: "Engineering standup starts at 9:00 AM.",
        type: "meeting",
        createdAt: day(0, 7),
        read: false,
        href: "/dashboard/organisation/meetings",
      },
      {
        id: "n3",
        title: "Announcement",
        body: "Welcome to Organisation HQ",
        type: "announcement",
        createdAt: day(-2, 12),
        read: true,
        href: "/dashboard/organisation/announcements",
      },
    ],
    channels: [
      { id: "ch1", name: "general", kind: "general" },
      { id: "ch2", name: "engineering", departmentId: "d1", kind: "department" },
      { id: "ch3", name: "people", departmentId: "d2", kind: "department" },
    ],
    messages: [
      {
        id: "msg1",
        channelId: "ch1",
        authorId: "e4",
        text: "Organisation HQ is live — explore your dashboard and keep feedback coming!",
        at: day(-2, 11),
      },
      {
        id: "msg2",
        channelId: "ch2",
        authorId: "e2",
        text: "Standup at 9. Bring one blocker and one win.",
        at: day(-1, 18),
      },
      {
        id: "msg3",
        channelId: "ch2",
        authorId: "e3",
        text: "Accessibility checklist is almost ready for review.",
        at: day(0, 8),
      },
    ],
  };
}
